name = "cuid2_gleam"
version = "1.0.1"
description = "Reimplementation of paralleldrive/cuid2 in Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "fravan", repo = "cuid2_gleam" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
